# Generated by Django 3.2.5 on 2021-07-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ask',
            old_name='post',
            new_name='hospital',
        ),
    ]
